version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed on `date`
  artifacts:
    files:
      - build/libs/*
    discard-paths: yes
